# Generated by Django 5.0.3 on 2024-04-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_create_date_alter_course_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='course/course/'),
            preserve_default=False,
        ),
    ]
